parameters:
    spiiicy_flightstats.class: Spiiicy\Bundle\FlightStatsBundle\FlightStats\FlightStats

services:
    spiiicy_flightstats:
      class: %spiiicy_flightstats.class%
      arguments: [%spiiicy_flight_stats.config%]