parameters:
    uww_flightstats.class: UnitedWorldWrestling\Bundle\FlightStatsBundle\FlightStats\FlightStats

services:
    uww_flightstats:
      class: %uww_flightstats.class%
      arguments: [%united_world_wrestling_flight_stats.config%]